language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: philip_glebow@gap.com
  password:
    secure: jE2vGPjJhBAL5TQCODKhnhhVO+9F539pFDgnkXxQghZrXj0VGAgMvs2PaRwhWwWUoRe7Pbo5PDyMcMgOAWaQVv2SBEE7ivdnkei1ksQ56EkxsRt9HnwRyfwUkNOwwvxm/kKdH/GbSnCtSSrKOTJfdJ7Et0eI807KGw8cjXka3Rj8hEJ1MRJG+A+LNx40MhBjYZa+eS7v2e2jwkIreYBYHQo5isT3WUL8YPc978RCZVzYat4GyR8xS9w7bpFgA7ApSeoGrjYpjSwvBgrVeSJB/3d6uD7e6068V4qlGrBuDT11ZevPufImPc2b/2JZmdcb9uzFUoJJPTV5yshrmh0g4U2cjTugB0gRJUIopOeus2bs1dC1MecvEfkmChcHZ7UKdMnPu1d2eqYPha24BjUSzlNsdkEUO9otp0ibL8hdrg3bXTt4wiIubIOBFUNinIzAwfQ0ppfL3x2QHTguK9PuaE/pT0LrXM3ZMifyXfbDnfj0/GLXOZf2x27YUL1t44ITTkSiaoN65D+Ab3UvC6X2n7ZmEREjmADw6ux/rQxKRwS0cU46qGoJsix9MO2Hab8ro9nZffPQZ8lHZuyIK+O1Fq1fySZTVX86bHIUtc1Tm1X33Yyxgxl/fKCB5O/UWRTHVurjqZTFnbR9cxdc1vB5gybDWG+u8CRCYLoR0T2wmSQ=
  organization: pglebow
  space: development
  on:
    repo: pglebow/rest-data
