language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: philip_glebow@gap.com
  password:
    secure: IYboK2kPh3TjonQlMhPiBYJSn6DAcNAW7mnYM2E2CMTNN3A/t4S/vPVyqZiIwEmz6tmWCO9CLJ6evMiwPss2S3y1d9/R5jRXrQimkcU2N71wVdnSYZVr8q4MPqKNvZ1iTPREqfxoP3A9c/7PIcE9wsl0/WDp8NSZy1f0V6wqnBu5Lccnzuz0iqCtCXbDONLgzruKCWhFjut7pS2xUMuHDFhESqNRtL6KXCQ4iIlxNd1BhgtjfC/h3HbIopJ/opmRSXqlmM+L0+N0NkaK+usB7c4dBGvXp2LlvXJUnoOO+jjoMJY+HjyeYFdsNr3cAnMKLSTVZ1t+GGas35g/lINEZDbxuku7oO34tq0Micc+ApaPLgYaMgtuDjyX3/oVTEea58f/k6PiYPpV9E3u76+MwaSNbmsmjWY+rjTDI+O63xqG2FKJcUv/UOXCLWWegL4lNccVCDboLQq4dEVaq/1yV7vs7bRH8cHlWYm2HZvYVGdFha9aqWxX0uvLy7to9ITBLus7ElRpfAKh2aTAZfuSQcWhW5zwJ7oNAJ2P2LX0ifIC3tu4Zfp77HVMy4W4RNTepJ5hdXklHHALuuPBLZNSUd5yeh2WEx/o3WXt0GXaIHdr4INHeZ2bcawOvQ+nmISqDDFIOVf1+9sJpvmRy/jC6goPMVQ1ueHo4ArDwAk5OSA=
  organization: pglebow
  space: development
  on:
    repo: pglebow/rest-data
